channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=openblas
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.19.1=hb547adb_0
  - ca-certificates=2023.7.22=hf0a4a13_0
  - cairo=1.16.0=h29d4eff_2
  - eigen=3.4.0=hc021e02_0
  - fontconfig=2.13.94=heb65262_0
  - freetype=2.10.4=h17b34a0_1
  - gettext=0.21.1=h0186832_0
  - giflib=5.2.1=h1a8c8d9_3
  - glib=2.69.1=h514c7bf_2
  - graphite2=1.3.14=hc377ac9_1
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - harfbuzz=4.3.0=he9eebac_1
  - hdf5=1.12.1=h05c076b_3
  - icu=68.2=hbdafb3b_0
  - jpeg=9e=h1a8c8d9_3
  - krb5=1.20.1=h69eda48_0
  - lcms2=2.15=h481adae_0
  - lerc=3.0=hc377ac9_0
  - libclang=12.0.0=default_hc321e17_4
  - libcurl=8.1.1=h3e2b118_2
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.17=he4db4b2_0
  - libllvm12=12.0.1=h93073aa_2
  - libnghttp2=1.52.0=h62f6fdd_1
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libpq=12.15=h02f6b3c_1
  - libssh2=1.10.0=h02f6b3c_2
  - libtiff=4.5.0=h313beb8_2
  - libwebp=1.2.4=ha3663a8_1
  - libwebp-base=1.2.4=h80987f9_1
  - libxml2=2.10.3=h372ba2a_0
  - libxslt=1.1.37=h1bd8bc4_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=hb7217d7_0
  - ncurses=6.4=h313beb8_0
  - nspr=4.35=hb7217d7_0
  - nss=3.89.1=h313beb8_0
  - numpy=1.25.2=py310h3b2db8e_0
  - numpy-base=1.25.2=py310ha9811e2_0
  - opencv=4.6.0=py310he2359d5_2
  - openssl=3.1.2=h53f4e23_0
  - pcre=8.45=hbdafb3b_0
  - pillow=9.4.0=py310h313beb8_0
  - pip=23.2.1=py310hca03da5_0
  - pixman=0.40.0=h27ca646_0
  - python=3.10.12=hb885b13_0
  - qt-main=5.15.2=ha2d02b5_7
  - qt-webengine=5.15.9=h2903aaf_4
  - qtwebkit=5.212=h19f419d_5
  - readline=8.2=h1a28f6b_0
  - setuptools=68.0.0=py310hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - tk=8.6.12=hb8d0fd4_0
  - tzdata=2023c=h04d1e81_0
  - wheel=0.38.4=py310hca03da5_0
  - xz=5.4.2=h80987f9_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
